### ISSUE TITLE
Change city/church token to a tall cylinder (update rules, map and images)

### ISSUE THREAD

**Issue by garykac** [garykac/shinjuku#20]
- [x] Recreate images - tracked in #36
- [x] Update main rules - tracked in #36
- [x] Update quickstart rules- tracked in #36
- [x] Update readme.md
- [x] Update Map
- [x] Update cards - tracked in #32
- [x] Update print-n-play instructions
- [x] Update player screen

**Comment by garykac** [comment]
As part of this, the stations that can be upgraded to a dept store need to be updated to use the new Sakura icon.
