### ISSUE TITLE
Can we remove the need for different player setup based on player count?

### ISSUE THREAD

**Issue by garykac** [garykac/shinjuku#25]
Eliminating the need to have different setup for different player counts would simplify the initial game setup.

Currently, the game rules are:
* 2 player: 3 dept stores, 8 stores, 16 track
* 3 player: 2 dept stores, 7 stores, 13 track
* 4 player: 2 dept stores, 6 stores, 10 track

### Dept Stores

3 dept stores are necessary for 2 player, but are not likely to be used in 3- and 4-player. However, including them at those player counts isn't a problem because it will be challenging to be able to build them. And if someone can successfully do that, that sounds awesome.

### Stores

The current approach of reducing the store count based on player count is
* _tedious_ since you have to refer to the rules and select the correct stores to remove
* _odd_ since only electronics and book stores are removed. This is because they are the rarest customer type, but it still feels a bit arbitrary.

We need 2 stores of each type, but having more stores is not a real problem since we don't need this to be component-limited in higher player count games because there are fewer opportunities to use them.

So having all 8 stores (4 of each type) regardless of player count seems fine.

### Track

Track is the only component that needs to vary based on player count.

More track is needed per-player in the low-player-count games than in games with more players.
But track needs to be restricted in higher player count games so that it isn't too easy to simply route around opponent's stores.

## Proposal for track

Each player has 9 track of their color regardless of player count.

In a 4-player game, this is basically the same as the current rules (changing 10 to 9 track).

In a 2- and 3-player game, the unused player colors are placed in a pool of "neutral track".

When you build single track, you must build with your color track. If you are out of track, then you cannot build. (This is the same as the current rule)

When building multiple track on the same action, the first track placed must match your color, but after that initial piece, the track **may** be taken from the shared neutral pool.

When neutral track is used during a Move action, it does not generate Income for anyone.

The proposal would reduce the total track components from 64 (= 16 x4 players) to 36 (= 9 x4 players).

**Comment by garykac** [comment]
Department stores and regular stores can be normalized for all player counts, but track is harder.

Move this track proposal into an Expansion. Tracking in #33

**Comment by garykac** [comment]
Using this issue to track updating the rules for stores and dept stores

- [x] Update main rules - tracked in #36
- [x] Update quickstart - tracked in #36
- [x] Update player screen - tracked in #35
