### ISSUE TITLE
Update rules (to v12)

### ISSUE THREAD

**Issue by garykac** [garykac/shinjuku#36]
Main rules
- [x] Regenerate images that show map or dept store icon
- [x] Update references to dept store icon
- [x] Update player piece setup (only track varies)
- [x] Remove discard at start of Income
- [x] Remove recommendation to play with Princess Mod for first game
- [x] Allow double track build with single card (see #26)
- [x] Don't use "sacrifice" or "spend" in description for Upgrading to dept store (see #28)
- [x] Be explicit about double track builds through Shinjuku-Yoyogi (see #27)
- [x] Make sure each figure has a caption
- [x] Update BGG

Quick start
- [x] Update references to dept store icon
- [x] Update player piece setup (only track varies)
- [x] Remove discard at start of Income
- [x] Remove recommendation to play with Princess Mod for first game
- [x] Allow double track build with single card (see #26)
- [x] Don't use "sacrifice" or "spend" in description for Upgrading to dept store (see #28)
- [x] Update BGG
