### ISSUE TITLE
Rule update: 72 customers

### ISSUE THREAD

**Issue by garykac** [garykac/shinjuku#73]
Go back to 72 customers now that we're seeding the board with customers at the start.

Update:
* [x] Main rulebook
* [x] Quickstart guide
* [x] readme.md
* [x] PNP instructions
* [x] PNP sticker sheet
* [x] ~~Tabletop Simulator~~ - Moved to #80
* [x] ~~Tabletopia~~ - Moved to #81
* [x] ~~screentop.gg~~ - Moved to #82
